In [37]:
import pandas as pd
bs = pd.read_json("data_master/resources/berniesanders.json",lines=True)
bstweets = bs["full_text"]
t1_df= pd.DataFrame(bstweets)
t1_df = t1_df.rename(columns={'full_text': 'tweet'})
t1_df.insert(0, 'Political Affiliation', 'Democrats')
t1_df.insert(2, 'Politician', 'Bernie Sanders')
count = t1_df['tweet'].str.split().str.len()
t1_df['Word Count']=count
t1_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Democrats,RT @CoriBush: The forward thinking &amp; coura...,Bernie Sanders,21
1,Democrats,"My skeptics often accuse me of being boring, o...",Bernie Sanders,47
2,Democrats,Let's call this what it is: a racist and uncon...,Bernie Sanders,27
3,Democrats,RT @amy4thepeople: @BernieSanders @CoriBush @p...,Bernie Sanders,20
4,Democrats,"When we are in the White House, we will have t...",Bernie Sanders,42

In [41]:
t1woRT_df =t1_df[~t1_df.tweet.str.contains("RT")]
t1woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
1,Democrats,"My skeptics often accuse me of being boring, o...",Bernie Sanders,47
2,Democrats,Let's call this what it is: a racist and uncon...,Bernie Sanders,27
4,Democrats,"When we are in the White House, we will have t...",Bernie Sanders,42
6,Democrats,"Thank you @CoriBush, @paulajean2020, and @amy4...",Bernie Sanders,29
9,Democrats,Today on #Stonewall50 we honor the brave peopl...,Bernie Sanders,36

In [42]:
t1woRT_df.to_csv("data_master/resources/berniesanders_ft.csv", index=False)

In [44]:
hd = pd.read_json("data_master/resources/housedemocrats.json",lines=True)
hdtweets = hd["full_text"]
t2_df= pd.DataFrame(hdtweets)
t2_df = t2_df.rename(columns={'full_text': 'tweet'})
t2_df.insert(0, 'Political Affiliation', 'Democrats')
t2_df.insert(2, 'Politician', 'House of Democrats')
count = t2_df['tweet'].str.split().str.len()
t2_df['Word Count']=count
t2woRT_df =t2_df[~t2_df.tweet.str.contains("RT")]
t2woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Democrats,NO American should worry about the cost of lif...,House of Democrats,36
4,Democrats,ALL American families deserve to live in safe ...,House of Democrats,37
6,Democrats,A targeted attack on our democracy is no laugh...,House of Democrats,41
7,Democrats,House Democrats are FOCUSED on protecting our ...,House of Democrats,28
8,Democrats,Mental health care is health care. We must pro...,House of Democrats,40

In [45]:
t2woRT_df.to_csv("data_master/resources/housedemocrats_ft.csv", index=False)

In [47]:
hg = pd.read_json("data_master/resources/housegop.json",lines=True)
hgtweets = hg["full_text"]
t3_df= pd.DataFrame(hdtweets)
t3_df = t3_df.rename(columns={'full_text': 'tweet'})
t3_df.insert(0, 'Political Affiliation', 'Republican')
t3_df.insert(2, 'Politician', 'House of Republican')
count = t3_df['tweet'].str.split().str.len()
t3_df['Word Count']=count
t3woRT_df =t3_df[~t3_df.tweet.str.contains("RT")]
t3woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,NO American should worry about the cost of lif...,House of Republican,36
4,Republican,ALL American families deserve to live in safe ...,House of Republican,37
6,Republican,A targeted attack on our democracy is no laugh...,House of Republican,41
7,Republican,House Democrats are FOCUSED on protecting our ...,House of Republican,28
8,Republican,Mental health care is health care. We must pro...,House of Republican,40

In [48]:
t3woRT_df.to_csv("data_master/resources/housegop_ft.csv", index=False)

In [50]:
jb = pd.read_json("data_master/resources/joebiden.json",lines=True)
jbtweets = jb["full_text"]
t4_df= pd.DataFrame(jbtweets)
t4_df = t4_df.rename(columns={'full_text': 'tweet'})
t4_df.insert(0, 'Political Affiliation', 'Democrats')
t4_df.insert(2, 'Politician', 'Joe Biden')
count = t4_df['tweet'].str.split().str.len()
t4_df['Word Count']=count
t4woRT_df =t4_df[~t4_df.tweet.str.contains("RT")]
t4woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Democrats,We're in a battle for the soul of this nation....,Joe Biden,46
2,Democrats,Today marks 50 years since the Stonewall upris...,Joe Biden,45
3,Democrats,I’ve fought my heart out to ensure that civil ...,Joe Biden,50
5,Democrats,"At last night’s first Democratic debate, I lai...",Joe Biden,43
6,Democrats,"I just got off the debate stage, where I laid ...",Joe Biden,51

In [51]:
t4woRT_df.to_csv("data_master/resources/joebiden_ft.csv", index=False)

In [52]:
lc = pd.read_json("data_master/resources/Liz_Cheney.json",lines=True)
lctweets = lc["full_text"]
t5_df= pd.DataFrame(lctweets)
t5_df = t5_df.rename(columns={'full_text': 'tweet'})
t5_df.insert(0, 'Political Affiliation', 'Republican')
t5_df.insert(2, 'Politician', 'Liz Cheney')
count = t5_df['tweet'].str.split().str.len()
t5_df['Word Count']=count
t5woRT_df =t5_df[~t5_df.tweet.str.contains("RT")]
t5woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,Congratulations @USWNT! https://t.co/wFi3kQggjz,Liz Cheney,3
2,Republican,Main take away from #DemDebates: \n2020 Democr...,Liz Cheney,34
5,Republican,Listen and learn @AOC https://t.co/nq5CMyu8NT,Liz Cheney,5
6,Republican,Happy to help educate you @AOC. You could star...,Liz Cheney,35
7,Republican,Please @AOC do us all a favor and spend just a...,Liz Cheney,37

In [53]:
t5woRT_df.to_csv("data_master/resources/lizcheney_ft.csv", index=False)

In [54]:
mr = pd.read_json("data_master/resources/marcorubio.json",lines=True)
mrtweets = mr["full_text"]
t6_df= pd.DataFrame(mrtweets)
t6_df = t6_df.rename(columns={'full_text': 'tweet'})
t6_df.insert(0, 'Political Affiliation', 'Republican')
t6_df.insert(2, 'Politician', 'Marco Rubio')
count = t6_df['tweet'].str.split().str.len()
t6_df['Word Count']=count
t6woRT_df =t6_df[~t6_df.tweet.str.contains("RT")]
t6woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,Q:Are you taking #Huawei off entity list?\n \n...,Marco Rubio,41
1,Republican,If President Trump has in fact bargained away ...,Marco Rubio,37
2,Republican,If President Trump has agreed to reverse recen...,Marco Rubio,41
3,Republican,US sanctions Maduro’s son as it raises pressur...,Marco Rubio,11
4,Republican,If America becomes a country that no longer ca...,Marco Rubio,36

In [55]:
t6woRT_df.to_csv("data_master/resources/marcorubio_ft.csv", index=False)

In [56]:
mp = pd.read_json("data_master/resources/mike_pence.json",lines=True)
mptweets = mp["full_text"]
t7_df= pd.DataFrame(mrtweets)
t7_df = t7_df.rename(columns={'full_text': 'tweet'})
t7_df.insert(0, 'Political Affiliation', 'Republican')
t7_df.insert(2, 'Politician', 'Mike Pence')
count = t7_df['tweet'].str.split().str.len()
t7_df['Word Count']=count
t7woRT_df =t7_df[~t7_df.tweet.str.contains("RT")]
t7woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,Q:Are you taking #Huawei off entity list?\n \n...,Mike Pence,41
1,Republican,If President Trump has in fact bargained away ...,Mike Pence,37
2,Republican,If President Trump has agreed to reverse recen...,Mike Pence,41
3,Republican,US sanctions Maduro’s son as it raises pressur...,Mike Pence,11
4,Republican,If America becomes a country that no longer ca...,Mike Pence,36

In [57]:
t7woRT_df.to_csv("data_master/resources/mikepence_ft.csv", index=False)

In [59]:
dt = pd.read_json("data_master/resources/realDonaldTrump.json",lines=True)
dttweets = dt["full_text"]
t8_df= pd.DataFrame(dttweets)
t8_df = t8_df.rename(columns={'full_text': 'tweet'})
t8_df.insert(0, 'Political Affiliation', 'Republican')
t8_df.insert(2, 'Politician', 'Donald Trump')
count = t8_df['tweet'].str.split().str.len()
t8_df['Word Count']=count
t8woRT_df =t8_df[~t8_df.tweet.str.contains("RT")]
t8woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,Thank you #G20OsakaSummit https://t.co/9FCqSuR5Bp,Donald Trump,4
1,Republican,"After some very important meetings, including ...",Donald Trump,49
2,Republican,54% in Poll! I would be at 75% (with our great...,Donald Trump,28
3,Republican,"I am in Japan at the G-20, representing our Co...",Donald Trump,39
4,Republican,The Stock Market went up massively from the da...,Donald Trump,56

In [60]:
t8woRT_df.to_csv("data_master/resources/donaldtrump_ft.csv", index=False)

In [61]:
sd = pd.read_json("data_master/resources/SenateDems.json",lines=True)
sdtweets = sd["full_text"]
t9_df= pd.DataFrame(sdtweets)
t9_df = t9_df.rename(columns={'full_text': 'tweet'})
t9_df.insert(0, 'Political Affiliation', 'Democrats')
t9_df.insert(2, 'Politician', 'Senate of Democrats')
count = t9_df['tweet'].str.split().str.len()
t9_df['Word Count']=count
t9woRT_df =t9_df[~t9_df.tweet.str.contains("RT")]
t9woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
5,Democrats,“We should insist that we have the authority a...,Senate of Democrats,31
6,Democrats,"“To date, the administration seems to have tri...",Senate of Democrats,36
7,Democrats,WATCH: @SenJeffMerkley calls on senators to ho...,Senate of Democrats,22
8,Democrats,"“Tomorrow, we will all speak to a fundamental ...",Senate of Democrats,41
9,Democrats,“The Udall amendment would mark the beginning ...,Senate of Democrats,30

In [62]:
t9woRT_df.to_csv("data_master/resources/senatedemocrats_ft.csv", index=False)

In [64]:
sg = pd.read_json("data_master/resources/senategop.json",lines=True)
sgtweets = sg["full_text"]
t10_df= pd.DataFrame(sgtweets)
t10_df = t10_df.rename(columns={'full_text': 'tweet'})
t10_df.insert(0, 'Political Affiliation', 'Republican')
t10_df.insert(2, 'Politician', 'Senate of Republican')
count = t10_df['tweet'].str.split().str.len()
t10_df['Word Count']=count
t10woRT_df =t10_df[~t10_df.tweet.str.contains("RT")]
t10woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
1,Republican,"GREAT NEWS! This week, the Senate passed the b...",Senate of Republican,31
20,Republican,58 days.\n \n81 efforts blocked in the House.\...,Senate of Republican,25
27,Republican,✅ PASSED: The National Defense Authorization A...,Senate of Republican,29
33,Republican,.@HouseDemocrats: This crisis demands action. ...,Senate of Republican,10
41,Republican,"By an overwhelming 84-8 vote, the Senate just ...",Senate of Republican,37

In [65]:
t10woRT_df.to_csv("data_master/resources/senaterepublican_ft.csv", index=False)

In [67]:
sw = pd.read_json("data_master/resources/senwarren.json",lines=True)
swtweets = sw["full_text"]
t11_df= pd.DataFrame(swtweets)
t11_df = t11_df.rename(columns={'full_text': 'tweet'})
t11_df.insert(0, 'Political Affiliation', 'Democrats')
t11_df.insert(2, 'Politician', 'Senator Warren')
count = t11_df['tweet'].str.split().str.len()
t11_df['Word Count']=count
t11woRT_df =t11_df[~t11_df.tweet.str.contains("RT")]
t11woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Democrats,@CFPB @splcenter @RepKatiePorter @RepPressley ...,Senator Warren,40
1,Democrats,The @CFPB’s Director of the Office of Innovati...,Senator Warren,37
2,Democrats,"Whether @realDonaldTrump likes it or not, he n...",Senator Warren,42
3,Democrats,.@realDonaldTrump and his band of war hawks @S...,Senator Warren,36
4,Democrats,I wrote to @BalfourBeatty &amp; the @USAirForc...,Senator Warren,33

In [68]:
t11woRT_df.to_csv("data_master/resources/senwarren_ft.csv", index=False)

In [70]:
sw = pd.read_json("data_master/resources/tedcruz.json",lines=True)
swtweets = sw["full_text"]
t12_df= pd.DataFrame(swtweets)
t12_df = t12_df.rename(columns={'full_text': 'tweet'})
t12_df.insert(0, 'Political Affiliation', 'Republican')
t12_df.insert(2, 'Politician', 'Ted Cruz')
count = t11_df['tweet'].str.split().str.len()
t12_df['Word Count']=count
t12woRT_df =t12_df[~t12_df.tweet.str.contains("RT")]
t12woRT_df.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,Help #KeepTexasRed and build our majority in t...,Ted Cruz,40.0
11,Republican,We are going to defend freedom in the United S...,Ted Cruz,23.0
13,Republican,This is the ideological diversity of 2020 Dems...,Ted Cruz,40.0
14,Republican,"Occasionally, facts matter. But not on 2020 De...",Ted Cruz,38.0
16,Republican,True. https://t.co/7VqAB9SoX3,Ted Cruz,43.0

In [71]:
t12woRT_df.to_csv("data_master/resources/tedcruz_ft.csv", index=False)

In [74]:
#Democrats
merge12 = pd.merge(t1woRT_df,t2woRT_df, how = "outer")
merge49 = pd.merge(t4woRT_df,t9woRT_df,how = "outer")
merge1249 = pd.merge(merge49,merge12,how = "outer")
merge_democrats =pd.merge(merge1249,t11woRT_df,how = "outer")
merge_democrats.head()

,Political Affiliation,tweet,Politician,Word Count
0,Democrats,We're in a battle for the soul of this nation....,Joe Biden,46
1,Democrats,Today marks 50 years since the Stonewall upris...,Joe Biden,45
2,Democrats,I’ve fought my heart out to ensure that civil ...,Joe Biden,50
3,Democrats,"At last night’s first Democratic debate, I lai...",Joe Biden,43
4,Democrats,"I just got off the debate stage, where I laid ...",Joe Biden,51

In [76]:
merge_democrats.count()

Political Affiliation    9054
tweet                    9054
Politician               9054
Word Count               9054
dtype: int64

In [77]:
merge_democrats.to_csv("data_master/resources/democrats_ft.csv",index=False)

In [78]:
#Republican

merge35 = pd.merge(t3woRT_df,t5woRT_df, how = "outer")
merge67 = pd.merge(t6woRT_df,t7woRT_df,how = "outer")
merge810 = pd.merge(t8woRT_df,t10woRT_df,how = "outer")
merge3567 =pd.merge(merge35,merge67,how = "outer")
merge81012 =pd.merge(merge810,t12woRT_df,how = "outer")
merge_republican =pd.merge(merge3567,merge81012,how = "outer")
merge_republican.head()

,Political Affiliation,tweet,Politician,Word Count
0,Republican,NO American should worry about the cost of lif...,House of Republican,36.0
1,Republican,ALL American families deserve to live in safe ...,House of Republican,37.0
2,Republican,A targeted attack on our democracy is no laugh...,House of Republican,41.0
3,Republican,House Democrats are FOCUSED on protecting our ...,House of Republican,28.0
4,Republican,Mental health care is health care. We must pro...,House of Republican,40.0

In [79]:
merge_republican.count()

Political Affiliation    14448
tweet                    14448
Politician               14448
Word Count               14445
dtype: int64

In [80]:
merge_republican.to_csv("data_master/resources/republican_ft.csv",index=False)